version: '2'

services:
  db:
    image: postgres:9.5
    ports:
      - "5432:5432"
    networks:
      app:
        aliases:
          - postgres
    volumes:
      - ./init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
    environment:
        POSTGRES_USER: communityshare
        POSTGRES_PASSWORD: communityshare

  server:
    build: .
    working_dir: /communityshare
    ports:
      - "5000:5000"
      - "5002:5001"
    networks:
      app:
    volumes:
      - .:/communityshare
    privileged: true

networks:
  app:
